# Generated by Django 4.1.6 on 2023-02-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_adress',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
    ]
