# Generated by Django 4.1.6 on 2023-02-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_email_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
